[general]
fps_counter = false
audio_offset = 0
visual_offset = 0
language = "ja"
hard_judge = 108
touch_enabled = false
timer_frozen = true
judge_counter = false

[nameplate_1p]
name = 'どんちゃん'
title = 'ドンだーデビュー！'
dan = -1
gold = false

[nameplate_2p]
name = 'かつちゃん'
title = 'ドンだーデビュー！'
dan = -1
gold = false

[paths]
tja_path = ['Songs']
video_path = ['Videos']

[keys_1p]
exit_key = 'A'
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[keys_2p]
left_kat = ["Z"]
left_don = ["X"]
right_don = ["C"]
right_kat = ["V"]

[gamepad]
left_kat = [10]
left_don = [16]
right_don = [17]
right_kat = [12]

[audio]
# device_type: 0 = default, check console output from list_host_apis() for other options
# Windows users should generally pick 3 (WASAPI) and Linux users should pick 0 (ALSA)
device_type = 3
# sample_rate: -1 = use device default (usually 44100 or 48000)
sample_rate = -1
# buffer_size: Size in samples per audio buffer
# - 0 = let driver choose (may result in very small buffers with ASIO, typically 64)
buffer_size = 0
exclusive = false

[volume]
sound = 1.0
music = 1.0
voice = 1.0
hitsound = 1.0

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
target_fps = -1
vsync = true
